version: 2.1

jobs:
  build-linux-gcc:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: chmod u+x install_dependencies.sh && ./install_dependencies.sh
      - run: CC=gcc CXX=g++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-linux-clang:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: chmod u+x install_dependencies.sh && ./install_dependencies.sh clang
      - run: CC=clang CXX=clang++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-mac-gcc:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - run: chmod u+x install_dependencies.sh && ./install_dependencies.sh
      - run: CC=gcc CXX=g++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py
  build-mac-clang:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - run: chmod u+x install_dependencies.sh && ./install_dependencies.sh clang
      - run: CC=clang CXX=clang++ PYTHON=python3 make all
      - run: pushd erpcgen/test ; py.test ; popd
      - run: python3 test/run_unit_tests.py


workflows:
  build-workflow:
    jobs:
      - build-linux-gcc
      - build-linux-clang
      # - build-mac-gcc # Mac is on going, or it can be hosted on company computer.
      # - build-mac-clang
